import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';import {gunzipSync} from 'node:zlib';
const json=p=>JSON.parse(readFileSync(p,'utf8'));
const s=json('especificaciones/scene-spec.json'),v=json('especificaciones/design-variants.json'),l=json('public/assets/shared/layout.json');
const adjustments=json('especificaciones/ajustes-ejecutados.json');
assert.equal(s.coordinate_system.entry_to_window,'-Z');assert.equal(l.coordinateSystem.entry_to_window,'-Z');
assert.equal(v.designs.length,2);assert.deepEqual(v.designs.map(x=>x.id),['original','nuevo']);
assert(v.designs.every(d=>d.window_id===s.locked_rules.window_model_id));
const a=l.anchors,w=a.window_original_white_two_leaf;
assert.equal(w.leafCount,2);assert.equal(w.frame,'white');assert.deepEqual(w.position,s.window.opening_center_seed_m);
assert(a.cabinet_left_half_closed.position[2]>a.vanity_center.position[2]);assert(a.cabinet_right_open.position[2]<a.vanity_center.position[2]);
assert.equal(a.cabinet_left_half_closed.closedHeightFraction,.5);assert.equal(a.cabinet_right_open.closedHeightFraction,0);
assert.equal(a.toilet_shared.facing,'-X');assert(a.toilet_shared.position[2]+a.toilet_shared.size[2]/2<l.shower.backZ);
assert.deepEqual(a.vanity_center.position,s.vanity_wall_assembly.vanity_center.position_seed_m);
const assembly=adjustments.vanity_wall_assembly, centerZ=a.vanity_center.position[2];
for(const [id,direction] of [['cabinet_left_half_closed',1],['cabinet_right_open',-1]]){
  const c=a[id];assert.equal(c.size[2],assembly.side_cabinet_width_m);
  const gap=Math.abs(c.position[2]-centerZ)-c.size[2]/2-assembly.countertop_width_m/2;
  assert(Math.abs(gap-assembly.countertop_side_gap_m)<1e-8,`${id}: incorrect clear gap to countertop`);
  assert((c.position[2]-centerZ)*direction>0);assert(Math.abs(c.position[2]-centerZ)+c.size[2]/2<l.room.length_along_negative_z/2);
}
assert.equal(w.recessDepth,adjustments.window.usable_recess_depth_m);assert.equal(w.sillProjection,0);
assert(Math.abs(w.wallFaceZ-w.frameFrontZ-w.recessDepth)<1e-8);
assert.deepEqual(l.executedAdjustments,adjustments);
const b=gunzipSync(readFileSync('public/assets/shared/bano.glb.gz'));assert.equal(b.readUInt32LE(0),0x46546c67);const gltf=JSON.parse(b.subarray(20,20+b.readUInt32LE(12)).toString());
const names=gltf.nodes.map(n=>n.name);
for(const id of ['bano_static','reflector_original','reflector_nuevo','mirror_halo','glass_fixed','glass_sliding','glass_return','glass_front_return','window_glass_0','window_glass_1','exterior_tropical_depth'])assert(names.includes(id),`Missing node ${id}`);
const front=gltf.nodes.find(n=>n.name==='glass_front_return'),rear=gltf.nodes.find(n=>n.name==='glass_return');
const bounds=n=>gltf.accessors[gltf.meshes[n.mesh].primitives[0].attributes.POSITION];
const size=n=>bounds(n).max.map((v,i)=>v-bounds(n).min[i]);
assert(size(front).every((v,i)=>Math.abs(v-size(rear)[i])<1e-5),'Shower end panes must have identical dimensions');
assert(Math.abs(front.translation[2]-l.shower.frontZ)<1e-5);assert(Math.abs(size(front)[0]-s.shower.tray_width_x_seed_m)<1e-5);
const windowParts=gltf.nodes.filter(n=>n.extras?.moving==='window_sliding');
assert.equal(windowParts.length,8,'Moving sash must include four profiles, two seals, latch and glazing');
assert(windowParts.some(n=>n.name==='window_glass_0'));assert(windowParts.every(n=>n.extras.travelX===w.travelX));
assert(w.travelX>0.4&&w.travelX<0.5);assert.equal(w.operableLeaf,0);
const base=gltf.nodes.find(n=>n.name==='bano_static');assert(base.extras.baked);
assert(gltf.meshes[base.mesh].primitives.every(p=>p.attributes.TEXCOORD_1!==undefined),'Dedicated light UV missing');
assert(!gltf.images?.some(i=>i.uri?.startsWith('http')));assert(!gltf.extensionsRequired?.some(x=>x.includes('draco')||x.includes('meshopt')||x.includes('basisu')),'Unexpected decoder dependency');
console.log(`PASS — contract invariants, ${gltf.nodes.length} nodes, real mirror contours and UV1 checked against binary GLB.`);
